/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 28-Dec-2021 21:51:31 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */
DROP TABLE IF EXISTS `UserActions`
;

DROP TABLE IF EXISTS `UserProducts`
;
DROP TABLE IF EXISTS `Admin`
;

DROP TABLE IF EXISTS `Products`
;



DROP TABLE IF EXISTS `Users`
;

/* Create Tables */

CREATE TABLE `Admin`
(
	`idAdmin` INT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Admin` PRIMARY KEY (`idAdmin` ASC)
)

;

CREATE TABLE `Products`
(
	`idProduct` INT NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(20) NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`brand` VARCHAR(50) NOT NULL,
	`line` VARCHAR(50) NOT NULL,
	`price` VARCHAR(50) NULL,
	`description` TEXT NULL,
	`currency` VARCHAR(100) NULL,
	CONSTRAINT `PK_Products` PRIMARY KEY (`idProduct` ASC)
)

;

CREATE TABLE `UserActions`
(
	`idUserActions` INT NOT NULL AUTO_INCREMENT,
	`idUser` INT NOT NULL,
	`sessionNumber` VARCHAR(50) NULL,
	`timeLogin` TIMESTAMP NULL,
	`timeExit` TIMESTAMP NULL,
	`EnterFair` INT NULL,
	`EnterCheckOut` INT NULL,
	`DidTheOrder` INT NULL,
	`ip` VARCHAR(15) NULL,
	`Likes` TEXT NULL,
	`Dislikes` TEXT NULL,
	`Improvements` TEXT NULL,
	`ThingsWouldLike` TEXT NULL,
	`contactUs` INT NULL,
	`download` INT NULL,
	`city` VARCHAR(50) NULL,
	CONSTRAINT `PK_UserActions` PRIMARY KEY (`idUserActions` ASC)
)

;

CREATE TABLE `UserProducts`
(
	`idUser` INT NOT NULL,
	`idProduct` INT NOT NULL,
	`closeTime` INT NULL,
	`examineTime` INT NULL,
	`like` INT NULL,
	`addToCard` INT NULL,
	`Bought` INT NULL,
	`amountOrdered` INT NULL,
	CONSTRAINT `PK_UserProducts` PRIMARY KEY (`idUser` ASC, `idProduct` ASC)
)

;

CREATE TABLE `Users`
(
	`idUser` INT NOT NULL AUTO_INCREMENT,
	`NIT` VARCHAR(15) NULL,
	`email` VARCHAR(50) NULL,
	`phoneNumber` VARCHAR(50) NULL,
	CONSTRAINT `PK_Users` PRIMARY KEY (`idUser` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `UserActions`
 ADD INDEX `IXFK_UserActions_Users` (`idUser` ASC)
;

ALTER TABLE `UserProducts`
 ADD INDEX `IXFK_UserProducts_Products` (`idProduct` ASC)
;

ALTER TABLE `UserProducts`
 ADD INDEX `IXFK_UserProducts_Users` (`idUser` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `UserActions`
 ADD CONSTRAINT `FK_UserActions_Users`
	FOREIGN KEY (`idUser`) REFERENCES `Users` (`idUser`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `UserProducts`
 ADD CONSTRAINT `FK_UserProducts_Products`
	FOREIGN KEY (`idProduct`) REFERENCES `Products` (`idProduct`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `UserProducts`
 ADD CONSTRAINT `FK_UserProducts_Users`
	FOREIGN KEY (`idUser`) REFERENCES `Users` (`idUser`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;
